//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvaemCasaSimplificado {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Instrucoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Instrucoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProvaemCasaSimplificado.Instrucoes", typeof(Instrucoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando nova Jogada e/ou Operação..
        /// </summary>
        internal static string Aguardando {
            get {
                return ResourceManager.GetString("Aguardando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta não foi lançada, por favor jogue uma carta..
        /// </summary>
        internal static string CartaNaoLancada {
            get {
                return ResourceManager.GetString("CartaNaoLancada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maquina comprou {0} cartas..
        /// </summary>
        internal static string CartasCompradasMaquina {
            get {
                return ResourceManager.GetString("CartasCompradasMaquina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - Informa as regras do Jogo.
        ///D - Mostra os Comandos disponíveis
        ///S - Mostra as cartas em seu poder.
        ///C - Compra uma carta adicional para continuar o jogo.
        ///R - Mostra a carta que você terá de igualar.
        ///J - Mostra a carta em seu poder e Habilita digitar o nº da carta desejada para o jogo.
        ///N - Começa um novo Jogo.
        ///X - Finaliza o Jogo..
        /// </summary>
        internal static string Comandos {
            get {
                return ResourceManager.GetString("Comandos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogue uma carta para desafiar o participante..
        /// </summary>
        internal static string Desafio {
            get {
                return ResourceManager.GetString("Desafio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem vindo ao Jogo de Cartas GRADDA
        ///
        ///Instruções:
        ///
        ///Neste jogo vc sempre jogará contra o computador.
        ///Você receberá 7 cartas iniciais.
        ///O objetivo é finalizar todas as cartas que estiverem com você.
        ///Para isto, é necessário que apresente uma carta igual a que estiver sido mostrada pela máquina.
        ///Caso não tenha a carta igual a mostrada pela máquina, deverá comprar uma carta para continuar jogando.
        ///Você terá de comprar uma carta até o conseguir apresentar uma carta de mesmo naipe apresentada pela Máquina.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogada inválida, selecione outra carta ou compre do baralho..
        /// </summary>
        internal static string JogadaErro {
            get {
                return ResourceManager.GetString("JogadaErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta Jogada: {0}.
        /// </summary>
        internal static string JogadaMaquina {
            get {
                return ResourceManager.GetString("JogadaMaquina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogada realizada com sucesso.
        /// </summary>
        internal static string JogadaSucesso {
            get {
                return ResourceManager.GetString("JogadaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número da carta que deseja Jogar :.
        /// </summary>
        internal static string Jogar {
            get {
                return ResourceManager.GetString("Jogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta Retirada - {0}.
        /// </summary>
        internal static string MostrarCartaRetirada {
            get {
                return ResourceManager.GetString("MostrarCartaRetirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua vez de iniciar a jogada..
        /// </summary>
        internal static string NovaJogada {
            get {
                return ResourceManager.GetString("NovaJogada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este comando não existe, escolha entre um dos comandos listados:.
        /// </summary>
        internal static string OperacaoInvalida {
            get {
                return ResourceManager.GetString("OperacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você perdeu. Tente outra vez :-(.
        /// </summary>
        internal static string Perdedor {
            get {
                return ResourceManager.GetString("Perdedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ganhou. Parabéns, você é o cara!!! :-).
        /// </summary>
        internal static string Vencedor {
            get {
                return ResourceManager.GetString("Vencedor", resourceCulture);
            }
        }
    }
}
